// GENERATED CODE - DO NOT MODIFY BY HAND
// This is a simplified adapter for the Student model
// In production, this would be generated by build_runner

import 'package:brick_offline_first_with_supabase/brick_offline_first_with_supabase.dart';
import 'package:brick_sqlite/brick_sqlite.dart';
import 'package:brick_supabase/brick_supabase.dart';
import '../../models/student_brick.dart';

// Supabase Adapter
class StudentAdapter extends SupabaseAdapter<Student> {
  @override
  String get tableName => 'students';

  @override
  Future<Student> fromSupabase(Map<String, dynamic> data,
      {required SupabaseProvider provider, Query? query}) async {
    return Student(
      id: data['id'] as String,
      fullName: data['full_name'] as String?,
      grade: data['grade'] as String?,
      parentContact: data['parent_contact'] as String?,
      registrationDate: data['registration_date'] != null
          ? DateTime.parse(data['registration_date'] as String)
          : null,
      billingType: data['billing_type'] as String?,
      isActive: data['is_active'] as bool? ?? true,
      defaultFee: (data['default_fee'] as num?)?.toDouble(),
      adminUid: data['admin_uid'] as String?,
      paidTotal: (data['paid_total'] as num?)?.toDouble() ?? 0.0,
      owedTotal: (data['owed_total'] as num?)?.toDouble() ?? 0.0,
      subjects: data['subjects'] as String?,
    );
  }

  @override
  Future<Map<String, dynamic>> toSupabase(Student instance,
      {required SupabaseProvider provider, Query? query}) async {
    return {
      'id': instance.id,
      'full_name': instance.fullName,
      'grade': instance.grade,
      'parent_contact': instance.parentContact,
      'registration_date': instance.registrationDate?.toIso8601String(),
      'billing_type': instance.billingType,
      'is_active': instance.isActive,
      'default_fee': instance.defaultFee,
      'admin_uid': instance.adminUid,
      'paid_total': instance.paidTotal,
      'owed_total': instance.owedTotal,
      'subjects': instance.subjects,
    };
  }
}

// SQLite Adapter
class StudentSqliteAdapter extends SqliteAdapter<Student> {
  @override
  String get tableName => 'Student';

  @override
  Future<Student> fromSqlite(Map<String, dynamic> data,
      {required SqliteProvider provider, Query? query}) async {
    return Student(
      id: data['id'] as String,
      fullName: data['full_name'] as String?,
      grade: data['grade'] as String?,
      parentContact: data['parent_contact'] as String?,
      registrationDate: data['registration_date'] != null
          ? DateTime.fromMillisecondsSinceEpoch(data['registration_date'] as int)
          : null,
      billingType: data['billing_type'] as String?,
      isActive: (data['is_active'] as int) == 1,
      defaultFee: data['default_fee'] as double?,
      adminUid: data['admin_uid'] as String?,
      paidTotal: data['paid_total'] as double? ?? 0.0,
      owedTotal: data['owed_total'] as double? ?? 0.0,
      subjects: data['subjects'] as String?,
    );
  }

  @override
  Future<Map<String, dynamic>> toSqlite(Student instance,
      {required SqliteProvider provider, Query? query}) async {
    return {
      'id': instance.id,
      'full_name': instance.fullName,
      'grade': instance.grade,
      'parent_contact': instance.parentContact,
      'registration_date': instance.registrationDate?.millisecondsSinceEpoch,
      'billing_type': instance.billingType,
      'is_active': instance.isActive ? 1 : 0,
      'default_fee': instance.defaultFee,
      'admin_uid': instance.adminUid,
      'paid_total': instance.paidTotal,
      'owed_total': instance.owedTotal,
      'subjects': instance.subjects,
    };
  }

  @override
  final String primaryKeyName = 'id';

  @override
  final Map<String, String> fieldsToSqliteColumns = {
    'id': 'id',
    'fullName': 'full_name',
    'grade': 'grade',
    'parentContact': 'parent_contact',
    'registrationDate': 'registration_date',
    'billingType': 'billing_type',
    'isActive': 'is_active',
    'defaultFee': 'default_fee',
    'adminUid': 'admin_uid',
    'paidTotal': 'paid_total',
    'owedTotal': 'owed_total',
    'subjects': 'subjects',
  };
}

// Model Dictionary Entry
final studentModelDictionary = {
  Student: StudentAdapter(),
};

final studentSqliteDictionary = {
  Student: StudentSqliteAdapter(),
};
